version: "3"
services:

  models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - /HooGives:/app
    ports:
      - "8001:8000"
    networks:
      - backend
    command: bash -c "mod_wsgi-express start-server --working-directory /app/HooGives --reload-on-changes /app/HooGives/HooGives/wsgi.py"

networks:
  backend: